service: gcf-mongo-test # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs8
  project: mongo-test
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/mongo-test-87ea4609690f.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    # - node_modules/**
    - .gitignore
    # - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
